---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.11.18

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[kubectl::default]
    attributes:
