name 'kubectl'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures kubectl'
long_description 'Installs/Configures kubectl'
version '0.1.0'

issues_url 'https://github.com/dthorsen/chef-kubectl/issues'
source_url 'https://github.com/dthorsen/chef-kubectl'
