name 'kubectl'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures kubectl'
long_description 'Installs/Configures kubectl'
version '0.1.0'
